m3-t1
htmlacademy-javascript/1247033-code-and-magick-21 pull request #3
Opened 2020-10-02 18:04 UTC by EnjoyTWOS

2020-10-04 16:15 UTC, vitali-usik requested changes

2020-10-04 16:15 UTC, vitali-usik commented on js/setup.js
> +userDialog.classList.remove(`hidden`);
Вызов этой инструкции лучше завернуть в функцию и вызвать ее. Тем самым мы избавимся от кода "подвешенного в воздухе" и сможешь переиспользовать функцию в будущем

2020-10-04 16:15 UTC, vitali-usik commented on js/setup.js
> +const userDialog = document.querySelector(`.setup`);
Ко всем селеторам лучше добавлять постфикс `Element` или `Template`. Далее по коду будет проще понимать что содержится в переменной

2020-10-04 16:15 UTC, vitali-usik commented on js/setup.js
> +  let rand = Math.floor(Math.random() * arr.length);
const

2020-10-04 16:15 UTC, vitali-usik commented on js/setup.js
> +  for (let i = 0; i < 4; i++) {
4 в константы

2020-10-04 16:15 UTC, vitali-usik commented on js/setup.js
> +const fragment = document.createDocumentFragment();
Объявление вверх к объявлением всех переменных

2020-10-04 16:15 UTC, vitali-usik commented on js/setup.js
> +userDialog.querySelector(`.setup-similar`).classList.remove(`hidden`);
В функцию (смотри комментарий выше)

2020-10-04 16:15 UTC, vitali-usik commented on js/setup.js
> +renderWizardsArr();
Все вызовы функций лучше объединить в функции `init` и вызывать ее. Соответственно получим структуру:
- объявление переменных
- объявление функций
- вызов функций

2020-10-12 20:27 UTC, vitali-usik requested changes

2020-10-12 20:27 UTC, vitali-usik commented on js/setup.js
> +const wizardsQuantity = 4;
Uppercase

2020-10-12 20:27 UTC, vitali-usik commented on js/setup.js
> +similarListElement.appendChild(fragment);
В `init`

2020-11-02 16:34 UTC, EnjoyTWOS commented on js/setup.js
> +similarListElement.appendChild(fragment);
Как? оно же не будет работать

2020-11-03 18:26 UTC, vitali-usik approved these changes

2020-11-03 18:26 UTC, merged