m5-t1
htmlacademy-javascript/1247033-code-and-magick-21 pull request #5
Opened 2020-11-08 23:35 UTC by EnjoyTWOS

2020-11-09 18:33 UTC, vitali-usik requested changes

2020-11-09 18:33 UTC, vitali-usik commented on js/setup.js
> +  };
Экспорт значений в конце файла. Так же лучше создать переменные, а потом их экспортировать

2020-11-09 22:20 UTC, EnjoyTWOS commented on js/setup.js
> +  };
+

2020-11-10 17:57 UTC, vitali-usik approved these changes

2020-11-10 17:57 UTC, merged